# Site settings
title: Tideblog
email: mbrack@uni-koblenz.de
description: >
  Lol hello!
baseurl: ""
url: "https://github.com/TurboPope/tideblog"
github_username: turbopope
gems: [jekyll-assets]
collections:
  chapters:
    output: true
defaults:
  - scope:
      path: ""
      type: chapters
    values:
      layout: page

# Build settings
markdown: kramdown

# Ignore buildsystem files
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - bower_components
  - bower.json

assets:
  sources:
    - _assets/scss
    - _assets/js
    - bower_components/bootstrap/scss
    - bower_components/bootstrap/dist/js
    - bower_components/jquery/dist
