# Site settings
title: Tideblog
email: mbrack@uni-koblenz.de
description: >
  Lol hello
baseurl: ""
url: "https://turbopope.github.io/tideblog/"
github_username: turbopope
gems:
  - jekyll-sitemap
collections:
  chapters:
    output: true
defaults:
  - scope:
      path: ""
      type: chapters
    values:
      layout: page

# Build settings
markdown: kramdown
