# Site settings
title: Tideblog
email: mbrack@uni-koblenz.de
description: >
  Lol hello
baseurl: "/tideblog"
url: "https://turbopope.github.io/tideblog/"
github_username: turbopope
gems:
- jekyll-sitemap


# Build settings
markdown: kramdown
